// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpH3vwxzyA2FzdwxQ2cMcYxMvXdl_DjU',
    appId: '1:814575366772:web:14e9f3369d0f173992d721',
    messagingSenderId: '814575366772',
    projectId: 'suivivital-d2768d',
    authDomain: 'suivivital-d2768d.firebaseapp.com',
    databaseURL: 'https://suivivital-d2768d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suivivital-d2768d.appspot.com',
    measurementId: 'G-LXYTQ2KM9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBr9IizqMbuTPvzc2Y3RLMqqJent_fk2M',
    appId: '1:814575366772:android:21a137430e85a6ad92d721',
    messagingSenderId: '814575366772',
    projectId: 'suivivital-d2768d',
    databaseURL: 'https://suivivital-d2768d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suivivital-d2768d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARnhnP0lhN8dajrYe4V0JRUsYFB9WMeKA',
    appId: '1:814575366772:ios:cc2df69930860db292d721',
    messagingSenderId: '814575366772',
    projectId: 'suivivital-d2768d',
    databaseURL: 'https://suivivital-d2768d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suivivital-d2768d.appspot.com',
    iosBundleId: 'com.example.suivivital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARnhnP0lhN8dajrYe4V0JRUsYFB9WMeKA',
    appId: '1:814575366772:ios:207802825d60729c92d721',
    messagingSenderId: '814575366772',
    projectId: 'suivivital-d2768d',
    databaseURL: 'https://suivivital-d2768d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suivivital-d2768d.appspot.com',
    iosBundleId: 'com.example.suivivital.RunnerTests',
  );
}
